---
title: "STageR training"
author: "Alena van Bömmel"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(glmnet)
library(dplyr)
library(tidyverse)
library(tibble)
library(pheatmap)
library(ComplexHeatmap)
library(colortools)
library(circlize)
library(caret)
library(plotmo) # for plotting glmnet coeffs
library(ggsci)

col.heatmap <- c('#00429e', '#3761ac', '#5682bb', '#73a3c8', '#93c4d6', '#b9e5e3', '#ffffee', '#f3dad5', '#e3b7bc', '#d094a3', '#bc738a', '#a65272', '#90305a')

pal.age = c('#ffe877', '#d2af65', '#a77953', '#7c4540', '#52102d')
names(pal.age) = c("3M","9M","15M","24M","28M")

pal.age.gr = c('#ffe877', '#a77953', '#52102d')
names(pal.age.gr) = c("early","mid","late")

plot.dir <- "output"
clusters <- readRDS("../clock_cluster/clusters.rds")
```

## Data

```{r prepare data}
data <- readRDS("/misc/paras/data/maja/kiel/analysis/analysis_002/data4Alena/output/clusters_data.ind_211006.rds")
data.mat.orig <- data %>%
  column_to_rownames("co") %>%
  dplyr::select(- cluster)


Age <- colnames(data.mat.orig) %>% 
  str_extract("([:digit:])+M")
# change the geriatric age group
Age <- gsub("30M","28M",Age)

age <- as.numeric(gsub("M","",Age))

# 3 age groups
age.gr <- factor(case_when(Age=="3M" ~ 'early',
                          Age=="9M"|Age=="15M" ~ 'mid',
                          Age=="24M"|Age=="28M" ~ 'late'),levels=c('early','mid','late'))  

```

```{r original data}
### reduce the data into cluster values ####
data.clus <- data %>%
  group_by(cluster) %>%
  dplyr::summarise(across(starts_with("int"), ~ median(.x, na.rm = TRUE)))

data.cl <- t(data.clus[,-1])
colnames(data.cl) <- as.character(data.clus$cluster)
saveRDS(data.cl, "clock_cluster/cluster.median.Cs.rds")
```

## CROSS VALIDATION

```{r CV clock}
# cross validation using caret #
set.seed(19)

# create folds equally distributed in age groups
cv.estimation <- function(data, y, fd=5, sd=sample.int(100,size=1), alpha=0.5){
  set.seed(sd)
   sid.early <- createFolds(which(y=="early"), k = fd, list = FALSE, returnTrain = FALSE)
   sid.mid <- createFolds(which(y=="mid"), k = fd, list = FALSE, returnTrain = FALSE)
   sid.late <- createFolds(which(y=="late"), k = fd, list = FALSE, returnTrain = FALSE)
   
  a <- alpha
  betas.fd <- list()
   betas.fd.relaxed <- list()
  results.fd <- list()
  for (i in 1:fd){
    test.id <- sort(c(which(y=="early")[sid.early==i], 
                      which(y=="mid")[sid.mid==i], 
                      which(y=="late")[sid.late==i]))
    
    train.x <- data[-test.id,]
    train.y <- y[-test.id]
    cv.fit <- cv.glmnet(x=train.x, y=train.y, family="multinomial",type.measure="class", alpha=a,keep=FALSE,intercept=FALSE)
    # relaxed fit without regularisation
   # fit <- glmnet(x=train.x, y=train.y, family="multinomial",type.measure="class", alpha=a,keep=FALSE,intercept=FALSE, relax=T)
    fitted <- stats::predict(cv.fit, newx=data[test.id,],s="lambda.min",type="response")
    predicted <- apply(fitted,1, which.max)
    true <- y[test.id]
    results.fd[[i]] <- cbind(predicted,true)
    coefs <- coef(cv.fit, s = "lambda.min")
    betas.fd[[i]] <- sapply(coefs,function(x) as.matrix(x)) 
   # coefs.relaxed <- coef(fit$relaxed)
   #  betas.fd.relaxed[[i]] <- sapply(coefs.relaxed,function(x) x[,100]) 
    #lambdas.fd[[i]] <- fit$lambda
    #lambdas.min <- c(lambdas.min, cv.fit$lambda.min)
  }
  return(list(results.fd,betas.fd))
}

get.misclass <- function(pred, true){
  if (length(pred)!=length(true)) 
    stop("predicted and true must have the same length!")
  misclass= sum(pred!=true)/length(pred)
  return(misclass)
}

# repeat 10x 10-fold CV
 coefs.early <- c()
 coefs.mid <- c()
 coefs.late <- c()
 me.all <- c()
 results.fd <- list()
for (j in 1:10){
  cv.res <- cv.estimation(data.mat, y=age.gr, fd=10, sd=42+10*j, alpha=0.2) # sd=19
  results.fd <- append(results.fd,cv.res[[1]])
  betas.fd <- cv.res[[2]]

  # mean misclassification error 
  me.all <- c(me.all, sapply(cv.res[[1]], function(x) get.misclass(x[,1],x[,2])))

  ### convert the format of betas.fd to a list for each age group
  coefs.early <- cbind(coefs.early, sapply(betas.fd, function(x) x[,1]))
  coefs.mid <- cbind(coefs.mid, sapply(betas.fd, function(x) x[,2]))
  coefs.late <- cbind(coefs.late, sapply(betas.fd, function(x) x[,3]))
}
 
  coefs.all <- list()
 coefs.all[["early"]] <- coefs.early
 coefs.all[["mid"]] <- coefs.mid
  coefs.all[["late"]] <- coefs.late
  rownames(coefs.all[[1]]) <- c("intercept",colnames(data.mat))
  rownames(coefs.all[[2]]) <- c("intercept",colnames(data.mat))
  rownames(coefs.all[[3]]) <- c("intercept",colnames(data.mat))
 
```



## STageR using only 3 nonlinear clusters and GLM model

```{r STageR with 3 clusters}
# read the matrix of median values per cluster
data.cl <- readRDS("../clock_cluster/cluster.median.Cs.rds")
# use selected clusters
sel.clusters <- c("c2", "c3", "c4")
data.mat <- data.cl[, sel.clusters]

# repeat 10x 10-fold CV
 coefs.early <- c()
 coefs.mid <- c()
 coefs.late <- c()
 me.all <- c()
 results.fd <- list()
for (j in 1:10){
  cv.res <- cv.estimation(data.mat, y=age.gr, fd=10, sd=42+10*j, alpha=0.5) # sd=19
  results.fd <- append(results.fd,cv.res[[1]])
  betas.fd <- cv.res[[2]]

#write.table(sapply(results.fd, function(x) get.misclass(x[,1],x[,2])),
#            file.path(res.dir, "misclass.CV.slusters.elnet.4age.gr.nosel.orig.alpha05.caret.tsv"), sep="\t",quote=F)
#saveRDS(results.fd,
#            file.path(res.dir, "results.CV.clusters.elnet.5age.gr.orig.alpha05.caret.rds"))

  # mean misclassification error 
me.all <- c(me.all, sapply(cv.res[[1]], function(x) get.misclass(x[,1],x[,2])))

### convert the format of betas.fd to a list for each age group
coefs.early <- cbind(coefs.early, sapply(betas.fd, function(x) x[,1]))
  coefs.mid <- cbind(coefs.mid, sapply(betas.fd, function(x) x[,2]))
  coefs.late <- cbind(coefs.late, sapply(betas.fd, function(x) x[,3]))
}
 
  coefs.all <- list()
 coefs.all[["early"]] <- coefs.early
 coefs.all[["mid"]] <- coefs.mid
  coefs.all[["late"]] <- coefs.late
  rownames(coefs.all[[1]]) <- c("intercept",colnames(data.mat))
  rownames(coefs.all[[2]]) <- c("intercept",colnames(data.mat))
  rownames(coefs.all[[3]]) <- c("intercept",colnames(data.mat))
  

## FINAL MODEL ##
cv.fit <- cv.glmnet(x=data.mat, y=age.gr, family="multinomial",type.measure="class", 
                    alpha=0.5,keep=FALSE,intercept=FALSE,type.multinomial="ungrouped", relax=TRUE)

fit <- glmnet(x=data.mat, y=age.gr, family="multinomial",type.measure="class", 
                    alpha=0.5,keep=FALSE,intercept=FALSE,type.multinomial="ungrouped", relax=TRUE)

plot(fit, xvar = "lambda", label = TRUE, type.coef = "coef")
rel.fit <- fit$relaxed
```

##Plotting the coefficients

```{r boxplots with coefs}
coefs.all <- readRDS("coefs.all.STageR.final.rds")
  
  coefs.df <- data.frame()
  for (i in 1:length(coefs.all)){
    coefs.df <- coefs.df %>%
      bind_rows(reshape2::melt(coefs.all[[i]])) 
  }
  colnames(coefs.df) <- c("cluster","fold","beta")
  coefs.df <- coefs.df %>%
    mutate(stage = factor(rep(c("early","mid","late"),each=ncol(coefs.all[[1]])*nrow(coefs.all[[1]])),
                          levels=c("early","mid","late"))) %>%
    dplyr::filter(cluster !="intercept")

 
   ggplot(coefs.df, aes(x=stage, y=beta,fill=stage))+
    geom_boxplot()+
    geom_hline(yintercept=0,color="grey50",linetype=2)+
    scale_fill_manual(values=pal.age.gr)+
    #scale_x_discrete(guide = guide_axis(n.dodge = 1, angle=60, check.overlap=F))+
    facet_grid(~ cluster) + 
    theme_classic()+
    theme(legend.position = "bottom",
          axis.title.x=element_blank(),
          axis.text.x=element_text(size=12, angle=0),
          strip.text.x = element_text(size=12,
                                      face="bold")) 
```

```{r heatmap with coefs}
order.clus <- c("C2", "C3", "C4")
  
coefs.mat <- as.data.frame(sapply(coefs.all, rowMeans)) %>%
    rename_with(~ paste0(levels(age.gr),"")) %>%
    rownames_to_column("cluster") %>%
    dplyr::filter(cluster!="intercept") %>%
    mutate(cluster = factor(toupper(cluster), levels=order.clus)) %>%
  column_to_rownames("cluster")

# number of Cs in each cluster
no.cs.cluster <- clusters %>% 
  mutate(cluster = toupper(cluster)) %>%
  dplyr::filter(cluster %in% order.clus) %>%
    group_by(cluster) %>%
    tally() %>%
  as.data.frame()
rownames(no.cs.cluster) <- no.cs.cluster$cluster

# colors for the number of clusters
col.clusters = list(n = colorRamp2(c(0,3000,5100), # max(no.cs.cluster$n)),
                                   c("#FFFFFFFF","#7A7A7A","#000000")),# dark blue:c("#FFFFFFFF","#548096","#013249")
                    annotation_legend_param = list(n = list(at = c(0, 2000, 5000),
                                                title = "No of Cs")))

ha = HeatmapAnnotation(n=no.cs.cluster[,c("n")],
                   col=col.clusters, show_legend = c(TRUE,FALSE))  

ra = rowAnnotation(df=data.frame(stages = colnames(coefs.mat)),
                       col=list(stages=pal.age.gr), show_legend = FALSE)
mx.val <- max(-min(coefs.mat), max(coefs.mat))
col.heatmap <- colorRamp2(c(-mx.val, 0, mx.val), c('#00429e',"#F2F2F2FF",'#90305a')) 

Heatmap(t(as.matrix(coefs.mat)), 
        name = "Coef.", #column_title = "Coefficients in CV model", 
        cluster_columns = F, column_order = order.clus,
        cluster_rows = F,
        col = col.heatmap, 
        show_row_names=T, row_names_side = "left",
        left_annotation=ra, #top_annotation = ha
        column_names_gp = gpar(fontsize = 12),
        column_names_rot = 0, column_names_centered = T)
```

## Heatmap with median methylation values for STageR

```{r heatmap dat.mat}
#### methylation values in mean cluters
col.heatmap <- colorRamp2(c(0,0.5,1), c('#00429e',"#F2F2F2FF",'#90305a')) 
ra = rowAnnotation(stage=age.gr,
                   col=list(stage=c(early="#ffe877", mid="#d2af65",late="#52102d")), show_legend = TRUE)  

sample.names <- gsub("30M","28M",rownames(data.mat))
sample.names <- gsub("int_","",sample.names)
rownames(data.mat) <- sample.names

Heatmap(as.matrix(data.mat), 
        name = "Median methylation", #column_title = "Coefficients in CV model", 
        cluster_columns = T, #column_order = order.clus,
        cluster_rows = T,
        right_annotation = ra,
        col = col.heatmap, 
        show_row_names=T, row_names_side = "right",
        row_names_gp = gpar(fontsize = 10))
```

## Confusion matrix

```{r Confusion matrix}
### confusion matrix  #####
res.cv <- data.frame()
for (i in 1: length(results.fd)){
  res.cv <- rbind(res.cv,results.fd[[i]])
}

conf.mat <- table(res.cv)/colSums(table(res.cv))
colnames(conf.mat) <- c("early","mid","late")
rownames(conf.mat) <- colnames(conf.mat)

tb <- data.frame(stage = factor(rownames(conf.mat),levels=c("early","mid","late")))
rownames(tb) <- rownames(conf.mat)

cluster.cols <- list(stage=pal.age.gr) 

col.heatmap <- colorRampPalette(colors=c("white","grey30"))(21) 

pheatmap::pheatmap(100*as.matrix(conf.mat), 
                   show_rownames = F, show_colnames = F,
                   cluster_cols = F, cluster_rows = F, 
                   col = col.heatmap, 
                   annotation_row = tb, annotation_col = tb,
                   annotation_colors = cluster.cols, annotation_legend = F,
                   display_numbers = TRUE, number_format = "%.0f", number_color = "white", fontsize_number = 15) 
```

## Subsampling from the clusters

Subsampling in the test set only

```{r subsampling test set}
### sample nn CpGs from each cluster

### divide the samples in fd folds, then train on the training set using the full data and its median, test on the data using only a subsample (nn) of the CpGs in each cluster, repeat the subsampling N times.

cv.estimation.sampling.test <- function(data.median, data.full, y, 
                                   sd=sample.int(100,size=1), alpha=0.5,
                                   nn.seq=c(500,200,100,50,30,20,10,5),N=10, fd = 10){
  ## the samples on both data matrices must be identical in the same order
 stopifnot(rownames(data.median) == colnames(data.full)[-c(1:2)])
   set.seed(sd)
   sid.early <- createFolds(which(y=="early"), k = fd, list = FALSE, returnTrain = FALSE)
   sid.mid <- createFolds(which(y=="mid"), k = fd, list = FALSE, returnTrain = FALSE)
   sid.late <- createFolds(which(y=="late"), k = fd, list = FALSE, returnTrain = FALSE)
 
    
  a <- alpha
  results.fd <- list()
  for (i in 1:fd){
    test.id <- sort(c(which(y=="early")[sid.early==i], 
                      which(y=="mid")[sid.mid==i], 
                      which(y=="late")[sid.late==i]))
    
    train.x <- data.median[-test.id,]
    train.y <- y[-test.id]
    cv.fit <- cv.glmnet(x=train.x, y=train.y, family="multinomial",
                        type.measure="class", alpha=a, keep=FALSE,intercept=FALSE)
   
     ## sample nn CpGs from the original matrix of the test samples
    results.nn <- list()
    for (nn in nn.seq){
      # repeat each subsampling N times
      results <- c()
      for (j in 1:N){
        data.full.test <- data.full[,c("co","cluster",rownames(data.median)[test.id])] %>%
          group_by(cluster) %>%
          sample_n(nn) %>%
          dplyr::summarise(across(starts_with("int"), ~ median(.x, na.rm = TRUE)))
        data.cl.test <- t(data.full.test[,-1])
        colnames(data.cl.test) <- as.character(data.full.test$cluster)

        fitted <- stats::predict(cv.fit, newx=data.cl.test,s="lambda.min",type="response")
        predicted <- colnames(fitted)[apply(fitted,1, which.max)]
        true <- y[test.id]
        results <- results %>%
          bind_rows(bind_cols(predicted=predicted, true=as.character(true), round = rep(j, length(predicted))))
        }
      results.nn[[paste0(nn,"N")]] <- results
    }
    results.fd[[i]] <- results.nn
    }
  
  return(results.fd)
}

sel.clusters <- c("c2", "c3", "c4")
data.mat <- data.cl[, sel.clusters]

results.subsampling <- cv.estimation.sampling.test(data.median=data.mat, 
                       data.full=data %>% dplyr::filter(cluster %in% sel.clusters), 
                       y = age.gr, 
                       sd = 19, alpha=0.5,
                       nn.seq=c(2000,1000,500,200,100,50,30,10,5), N=10, fd = 10)

saveRDS(results.subsampling, "results.subsampling.STageR.test.final.rds")
```

## Plot the subsampling results

```{r plot subsampling}

get.error <- function(res){
    res.err <- res %>%
    group_by(round) %>%
    summarise(err = get.misclass(predicted,true))
    return(res.err)
}  

results.subsampling <- readRDS("results.subsampling.STageR.test.final.rds")
 err.fd <- c()
for (i in 1:length(results.subsampling)){
  res.fd <- results.subsampling[[i]]

  for (l in 1:length(res.fd)){
    err.fd <- err.fd %>%
      bind_rows(data.frame(get.error(res.fd[[l]]), no.cs = rep(names(res.fd)[l],max(res.fd[[l]]$round))))
  }
}  
 
 err.fd <- err.fd %>%
   mutate(no.cs.N = factor(gsub("N","",no.cs), levels=c("2000","1000","500","200","100","50","30","10","5")))

ggplot(err.fd, aes(x=no.cs.N, y=err, fill = no.cs.N)) +
  geom_boxplot() +
   scale_fill_manual(values=c('#000000', '#1e1e1e', '#353535', '#4e4e4e', '#696969', '#858585', '#a2a2a2', '#c0c0c0', '#dfdfdf'),guide=NULL) +
                     #c('#383838','#535353', '#6f6f6f', '#8c8c8c', '#ababab', '#ebebeb'),guide = NULL)+
    labs(y ="Misclassification error",
         x="Sampled CpGs per cluster")+
    theme_classic()+
    theme(axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size=13),
      axis.title.x = element_text(size=13))
 
# median values
err.fd %>%
  group_by(no.cs.N) %>%
  dplyr::summarize(median.err = median(err), mean.err = mean(err))
  
m.err <- cbind(m.err,(sapply(results.subsampling[[1]], function(x) get.misclass(x[,1],x[,2]))))


get.df <- function(mat, n.sampl){
  df.long <- as.data.frame(mat) %>%
    dplyr::mutate(cv = 1:nrow(mat)) %>%
    pivot_longer(cols = -cv,
                 names_to = "round",
                values_to = "error") %>%
    dplyr::mutate(N.sampl = n.sampl)
  return(df.long)
}

all.errors <- data.frame()

for (i in 1:length(m.err.ls)){
  all.errors <-rbind(all.errors, get.df(m.err.ls[[i]], names(m.err.ls)[i]))
} 

m.err.ls <- readRDS(file.path("subsampling.50.20.CpGs.CV.errors.allclusters.age.gr.5.alpha0.5.rds"))

for (i in 1:length(m.err.ls)){
  all.errors <-rbind(all.errors, get.df(m.err.ls[[i]], names(m.err.ls)[i]))
}

m.err.ls <- readRDS(file.path("subsampling.10.5.CpGs.CV.errors.allclusters.age.gr.5.alpha0.5.rds"))

for (i in 1:length(m.err.ls)){
  all.errors <-rbind(all.errors, get.df(m.err.ls[[i]], names(m.err.ls)[i]))
}


all.errors <- all.errors %>%
  mutate(N.sampl = factor(N.sampl,levels=c("500","200","100","50","20","10","5")))

ggplot(all.errors, aes(x=N.sampl, y=error, fill = N.sampl)) +
  geom_boxplot() +
   scale_fill_manual(values=c('#383838','#535353', '#6f6f6f', '#8c8c8c', '#ababab', '#8c8c8c', '#ebebeb'), # '#cacaca'
                     labels = c("500","200","100","50","20","10","5"), 
                     guide = NULL)+
    labs(y ="Misclassification error",x="")+
    theme_classic()+
    theme(axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size=13))


all.errors %>%
  dplyr::filter(N.sampl == "10") %>% 
  dplyr::summarise(sum = fivenum(error)) 
#  dplyr::summarise(q = quantile(error, 0.8))

all.errors %>%
  dplyr::filter(N.sampl == "5") %>% 
  dplyr::summarise(sum = fivenum(error)) 


```

